### ISSUE TITLE
Publish package to to npm registry

### ISSUE THREAD

**Issue by it-ony** [Adyen/adyen-3ds2-js#6]
Please publish the package to the npm registry. Also add a tag for the published version.

https://github.com/Adyen/adyen-3ds2-js/blob/e42048cb28a9caf2108465fead5648fe419aa79b/package.json#L3

**Comment by Trigalti** [comment]
Hey it-ony, thanks for all the feedback and issues. I have worked through most of them, but the approach to 3ds2.0 (and this repo) will most likely change (this being a helper repo). I will come with an update on any decision made at the end of this week. This includes deciding whether or not we will push this code to NPM and whether we keep this repo on Github or not.

**Comment by nudge** [comment]
Hi there, is using this package still supported or should we be using `Adyen/adyen-3ds2-js-utils` instead? Cheers.

**Comment by Trigalti** [comment]
> Hi there, is using this package still supported or should we be using [`Adyen/adyen-3ds2-js-utils` ](https://github.com/Adyen/adyen-3ds2-js-utils) instead? Cheers.

The idea is to indeed use the 3ds2-js-utils instead.

**Comment by Trigalti** [comment]
I will hereby also close this issue, since we do not intend to maintain nor publish this package to NPM.
